spring.application.name=ms-pacientes

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/db_pacientes
spring.datasource.username=postgres
spring.datasource.password=200304

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true